---
# Application: algocity-pathfinder
# Pipeline configuration for deploying algocity-pathfinder service

pipeline:
  stages:
    - name: Checkout Repositories
      steps:
        - clone_charts_repo
        - clone_values_repo
    
    - name: Build Docker Image
      steps:
        - build_image
        - tag_latest
        - push_to_registry
    
    - name: Deploy with Helm
      steps:
        - build_helm_dependencies
        - render_manifest
        - apply_to_k8s
